apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-k8s-net
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: git@your.git.host:you/obs-infra.git
    targetRevision: main
    path: deploy/opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
